// ============================================================================
// DATOS DE AEROLÍNEAS Y AEROPUERTOS
// ============================================================================
// Define las aerolíneas soportadas y sus aeropuertos disponibles.
// Actualizado con las 15 aerolíneas principales de EE.UU.
// ============================================================================

// Conjunto común de aeropuertos principales de EE.UU.
const AEROPUERTOS_PRINCIPALES_USA = [
    "ABQ", "AGS", "ALB", "AMA", "ANC", "ATL", "ATW", "AUS", "AVL", "BDL", "BGR", "BHM", "BIL", "BIS",
            "BNA", "BOI", "BOS", "BTR", "BTV", "BUF", "BUR", "BWI", "BZN", "CAE", "CHA", "CHO", "CHS",
    "CID", "CLE", "CLT", "CMH", "COS", "CRP", "CVG", "DAB", "DAL", "DAY", "DCA", "DEN", "DFW", "DLH",
    "DSM", "DTW", "ECP", "EGE", "ELP", "EWR", "EUG", "EYW", "FAI", "FAR", "FAT", "FAY", "FCA", "FLL",
            "FSD", "GEG", "GNV", "GPT", "GRB", "GRR", "GSO", "GSP", "HDN", "HNL", "HOU", "HPN", "HRL",
    "HSV", "IAD", "IAH", "ICT", "IDA", "ILM", "IND", "ISP", "ITO", "JAC", "JAN", "JAX", "JFK", "JNU", "KOA",
    "LAS", "LAX", "LBB", "LEX", "LGA", "LGB", "LIH", "LIT", "MAF", "MCI", "MCO", "MDT", "MDW", "MEM", "MHT",
    "MIA", "MKE", "MLB", "MOB", "MSN", "MSO", "MSP", "MSY", "MTJ", "MYR", "OAK", "OGG", "OKC", "OMA",
            "ONT", "ORD", "ORF", "PBI", "PDX", "PHL", "PHX", "PIT", "PNS", "PSC", "PSP", "PVD", "PWM",
            "RAP", "RDU", "RIC", "RNO", "ROA", "ROC", "RSW", "SAN", "SAT", "SAV", "SBA", "SBN", "SDF",
            "SEA", "SFO", "SGF", "SHV", "SJC", "SJU", "SLC", "SMF", "SNA", "SRQ", "STL", "STT", "STX",
            "SYR", "TLH", "TPA", "TRI", "TUL", "TUS", "TVC", "TYS", "VPS", "XNA"
];

const AIRLINE_DATA = {
    "9E": {
        "name": "Endeavor Air Inc. (9E)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "AA": {
        "name": "American Airlines Inc. (AA)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "AS": {
        "name": "Alaska Airlines Inc. (AS)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "B6": {
        "name": "JetBlue Airways (B6)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "DL": {
        "name": "Delta Air Lines Inc. (DL)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "F9": {
        "name": "Frontier Airlines Inc. (F9)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "G4": {
        "name": "Allegiant Air (G4)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "HA": {
        "name": "Hawaiian Airlines Inc. (HA)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "MQ": {
        "name": "Envoy Air (MQ)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "NK": {
        "name": "Spirit Air Lines (NK)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "OH": {
        "name": "PSA Airlines Inc. (OH)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "OO": {
        "name": "SkyWest Airlines Inc. (OO)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "UA": {
        "name": "United Air Lines Inc. (UA)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "WN": {
        "name": "Southwest Airlines Co. (WN)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    },
    "YX": {
        "name": "Republic Airline (YX)",
        "origenes": AEROPUERTOS_PRINCIPALES_USA,
        "destinos": AEROPUERTOS_PRINCIPALES_USA
    }
};

// Mapeo completo de códigos IATA a nombres y ciudades
// Basado en los datos de GeoUtils.java del backend
const AIRPORT_INFO = {
    "ABQ": { name: "Albuquerque International Sunport", city: "Albuquerque, NM" },
    "AGS": { name: "Augusta Regional at Bush Field", city: "Augusta, GA" },
    "ALB": { name: "Albany International Airport", city: "Albany, NY" },
    "AMA": { name: "Rick Husband Amarillo International Airport", city: "Amarillo, TX" },
    "ANC": { name: "Ted Stevens Anchorage International Airport", city: "Anchorage, AK" },
    "ATL": { name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta, GA" },
    "ATW": { name: "Appleton International Airport", city: "Appleton, WI" },
    "AUS": { name: "Austin-Bergstrom International Airport", city: "Austin, TX" },
    "AVL": { name: "Asheville Regional Airport", city: "Asheville, NC" },
    "BDL": { name: "Bradley International Airport", city: "Hartford, CT" },
    "BGR": { name: "Bangor International Airport", city: "Bangor, ME" },
    "BHM": { name: "Birmingham-Shuttlesworth International Airport", city: "Birmingham, AL" },
    "BIL": { name: "Billings Logan International Airport", city: "Billings, MT" },
    "BIS": { name: "Bismarck Municipal Airport", city: "Bismarck, ND" },
    "BNA": { name: "Nashville International Airport", city: "Nashville, TN" },
    "BOI": { name: "Boise Air Terminal/Gowen Field", city: "Boise, ID" },
    "BOS": { name: "Boston Logan International Airport", city: "Boston, MA" },
    "BTR": { name: "Baton Rouge Metropolitan Airport", city: "Baton Rouge, LA" },
    "BTV": { name: "Burlington International Airport", city: "Burlington, VT" },
    "BUF": { name: "Buffalo Niagara International Airport", city: "Buffalo, NY" },
    "BUR": { name: "Hollywood Burbank Airport", city: "Burbank, CA" },
    "BWI": { name: "Baltimore/Washington International Airport", city: "Baltimore, MD" },
    "BZN": { name: "Bozeman Yellowstone International Airport", city: "Bozeman, MT" },
    "CAE": { name: "Columbia Metropolitan Airport", city: "Columbia, SC" },
    "CHA": { name: "Lovell Field", city: "Chattanooga, TN" },
    "CHO": { name: "Charlottesville Albemarle Airport", city: "Charlottesville, VA" },
    "CHS": { name: "Charleston International Airport", city: "Charleston, SC" },
    "CID": { name: "The Eastern Iowa Airport", city: "Cedar Rapids, IA" },
    "CLE": { name: "Cleveland Hopkins International Airport", city: "Cleveland, OH" },
    "CLT": { name: "Charlotte Douglas International Airport", city: "Charlotte, NC" },
    "CMH": { name: "John Glenn Columbus International Airport", city: "Columbus, OH" },
    "COS": { name: "City of Colorado Springs Municipal Airport", city: "Colorado Springs, CO" },
    "CRP": { name: "Corpus Christi International Airport", city: "Corpus Christi, TX" },
    "CVG": { name: "Cincinnati/Northern Kentucky International Airport", city: "Cincinnati, OH" },
    "DAB": { name: "Daytona Beach International Airport", city: "Daytona Beach, FL" },
    "DAL": { name: "Dallas Love Field", city: "Dallas, TX" },
    "DAY": { name: "James M Cox Dayton International Airport", city: "Dayton, OH" },
    "DCA": { name: "Ronald Reagan Washington National Airport", city: "Washington, DC" },
    "DEN": { name: "Denver International Airport", city: "Denver, CO" },
    "DFW": { name: "Dallas/Fort Worth International Airport", city: "Dallas, TX" },
    "DLH": { name: "Duluth International Airport", city: "Duluth, MN" },
    "DSM": { name: "Des Moines International Airport", city: "Des Moines, IA" },
    "DTW": { name: "Detroit Metropolitan Wayne County Airport", city: "Detroit, MI" },
    "ECP": { name: "Northwest Florida Beaches International Airport", city: "Panama City, FL" },
    "EGE": { name: "Eagle County Regional Airport", city: "Eagle, CO" },
    "ELP": { name: "El Paso International Airport", city: "El Paso, TX" },
    "EWR": { name: "Newark Liberty International Airport", city: "Newark, NJ" },
    "EUG": { name: "Eugene Airport", city: "Eugene, OR" },
    "EYW": { name: "Key West International Airport", city: "Key West, FL" },
    "FAI": { name: "Fairbanks International Airport", city: "Fairbanks, AK" },
    "FAR": { name: "Hector International Airport", city: "Fargo, ND" },
    "FAT": { name: "Fresno Yosemite International Airport", city: "Fresno, CA" },
    "FAY": { name: "Fayetteville Regional Airport", city: "Fayetteville, NC" },
    "FCA": { name: "Glacier Park International Airport", city: "Kalispell, MT" },
    "FLL": { name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale, FL" },
    "FSD": { name: "Joe Foss Field", city: "Sioux Falls, SD" },
    "GEG": { name: "Spokane International Airport", city: "Spokane, WA" },
    "GNV": { name: "Gainesville Regional Airport", city: "Gainesville, FL" },
    "GPT": { name: "Gulfport-Biloxi International Airport", city: "Gulfport, MS" },
    "GRB": { name: "Green Bay Austin Straubel International Airport", city: "Green Bay, WI" },
    "GRR": { name: "Gerald R. Ford International Airport", city: "Grand Rapids, MI" },
    "GSO": { name: "Piedmont Triad International Airport", city: "Greensboro, NC" },
    "GSP": { name: "Greenville-Spartanburg International Airport", city: "Greenville, SC" },
    "HDN": { name: "Yampa Valley Airport", city: "Hayden, CO" },
    "HNL": { name: "Daniel K. Inouye International Airport", city: "Honolulu, HI" },
    "HOU": { name: "William P. Hobby Airport", city: "Houston, TX" },
    "HPN": { name: "Westchester County Airport", city: "White Plains, NY" },
    "HRL": { name: "Valley International Airport", city: "Harlingen, TX" },
    "HSV": { name: "Huntsville International Airport", city: "Huntsville, AL" },
    "IAD": { name: "Washington Dulles International Airport", city: "Washington, DC" },
    "IAH": { name: "George Bush Intercontinental Airport", city: "Houston, TX" },
    "ICT": { name: "Wichita Dwight D. Eisenhower National Airport", city: "Wichita, KS" },
    "IDA": { name: "Idaho Falls Regional Airport", city: "Idaho Falls, ID" },
    "ILM": { name: "Wilmington International Airport", city: "Wilmington, NC" },
    "IND": { name: "Indianapolis International Airport", city: "Indianapolis, IN" },
    "ISP": { name: "Long Island MacArthur Airport", city: "Islip, NY" },
    "ITO": { name: "Hilo International Airport", city: "Hilo, HI" },
    "JAC": { name: "Jackson Hole Airport", city: "Jackson, WY" },
    "JAN": { name: "Jackson-Medgar Wiley Evers International Airport", city: "Jackson, MS" },
    "JAX": { name: "Jacksonville International Airport", city: "Jacksonville, FL" },
    "JFK": { name: "John F. Kennedy International Airport", city: "New York, NY" },
    "JNU": { name: "Juneau International Airport", city: "Juneau, AK" },
    "KOA": { name: "Ellison Onizuka Kona International Airport", city: "Kailua-Kona, HI" },
    "LAS": { name: "Harry Reid International Airport", city: "Las Vegas, NV" },
    "LAX": { name: "Los Angeles International Airport", city: "Los Angeles, CA" },
    "LBB": { name: "Lubbock Preston Smith International Airport", city: "Lubbock, TX" },
    "LEX": { name: "Blue Grass Airport", city: "Lexington, KY" },
    "LGA": { name: "LaGuardia Airport", city: "New York, NY" },
    "LGB": { name: "Long Beach Airport", city: "Long Beach, CA" },
    "LIH": { name: "Lihue Airport", city: "Lihue, HI" },
    "LIT": { name: "Bill and Hillary Clinton National Airport", city: "Little Rock, AR" },
    "MAF": { name: "Midland International Air and Space Port", city: "Midland, TX" },
    "MCI": { name: "Kansas City International Airport", city: "Kansas City, MO" },
    "MCO": { name: "Orlando International Airport", city: "Orlando, FL" },
    "MDT": { name: "Harrisburg International Airport", city: "Harrisburg, PA" },
    "MDW": { name: "Chicago Midway International Airport", city: "Chicago, IL" },
    "MEM": { name: "Memphis International Airport", city: "Memphis, TN" },
    "MHT": { name: "Manchester-Boston Regional Airport", city: "Manchester, NH" },
    "MIA": { name: "Miami International Airport", city: "Miami, FL" },
    "MKE": { name: "General Mitchell International Airport", city: "Milwaukee, WI" },
    "MLB": { name: "Melbourne Orlando International Airport", city: "Melbourne, FL" },
    "MOB": { name: "Mobile Regional Airport", city: "Mobile, AL" },
    "MSN": { name: "Dane County Regional Airport", city: "Madison, WI" },
    "MSO": { name: "Missoula Montana Airport", city: "Missoula, MT" },
    "MSP": { name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis, MN" },
    "MSY": { name: "Louis Armstrong New Orleans International Airport", city: "New Orleans, LA" },
    "MTJ": { name: "Montrose Regional Airport", city: "Montrose, CO" },
    "MYR": { name: "Myrtle Beach International Airport", city: "Myrtle Beach, SC" },
    "OAK": { name: "Oakland International Airport", city: "Oakland, CA" },
    "OGG": { name: "Kahului Airport", city: "Kahului, HI" },
    "OKC": { name: "Will Rogers World Airport", city: "Oklahoma City, OK" },
    "OMA": { name: "Eppley Airfield", city: "Omaha, NE" },
    "ONT": { name: "Ontario International Airport", city: "Ontario, CA" },
    "ORD": { name: "O'Hare International Airport", city: "Chicago, IL" },
    "ORF": { name: "Norfolk International Airport", city: "Norfolk, VA" },
    "PBI": { name: "Palm Beach International Airport", city: "West Palm Beach, FL" },
    "PDX": { name: "Portland International Airport", city: "Portland, OR" },
    "PHL": { name: "Philadelphia International Airport", city: "Philadelphia, PA" },
    "PHX": { name: "Phoenix Sky Harbor International Airport", city: "Phoenix, AZ" },
    "PIT": { name: "Pittsburgh International Airport", city: "Pittsburgh, PA" },
    "PNS": { name: "Pensacola International Airport", city: "Pensacola, FL" },
    "PSC": { name: "Tri-Cities Airport", city: "Pasco, WA" },
    "PSP": { name: "Palm Springs International Airport", city: "Palm Springs, CA" },
    "PVD": { name: "Rhode Island T. F. Green International Airport", city: "Providence, RI" },
    "PWM": { name: "Portland International Jetport", city: "Portland, ME" },
    "RAP": { name: "Rapid City Regional Airport", city: "Rapid City, SD" },
    "RDU": { name: "Raleigh-Durham International Airport", city: "Raleigh, NC" },
    "RIC": { name: "Richmond International Airport", city: "Richmond, VA" },
    "RNO": { name: "Reno-Tahoe International Airport", city: "Reno, NV" },
    "ROA": { name: "Roanoke-Blacksburg Regional Airport", city: "Roanoke, VA" },
    "ROC": { name: "Greater Rochester International Airport", city: "Rochester, NY" },
    "RSW": { name: "Southwest Florida International Airport", city: "Fort Myers, FL" },
    "SAN": { name: "San Diego International Airport", city: "San Diego, CA" },
    "SAT": { name: "San Antonio International Airport", city: "San Antonio, TX" },
    "SAV": { name: "Savannah/Hilton Head International Airport", city: "Savannah, GA" },
    "SBA": { name: "Santa Barbara Municipal Airport", city: "Santa Barbara, CA" },
    "SBN": { name: "South Bend International Airport", city: "South Bend, IN" },
    "SDF": { name: "Louisville Muhammad Ali International Airport", city: "Louisville, KY" },
    "SEA": { name: "Seattle-Tacoma International Airport", city: "Seattle, WA" },
    "SFO": { name: "San Francisco International Airport", city: "San Francisco, CA" },
    "SGF": { name: "Springfield-Branson National Airport", city: "Springfield, MO" },
    "SHV": { name: "Shreveport Regional Airport", city: "Shreveport, LA" },
    "SJC": { name: "Norman Y. Mineta San Jose International Airport", city: "San Jose, CA" },
    "SJU": { name: "Luis Muñoz Marín International Airport", city: "San Juan, PR" },
    "SLC": { name: "Salt Lake City International Airport", city: "Salt Lake City, UT" },
    "SMF": { name: "Sacramento International Airport", city: "Sacramento, CA" },
    "SNA": { name: "John Wayne Airport", city: "Santa Ana, CA" },
    "SRQ": { name: "Sarasota Bradenton International Airport", city: "Sarasota, FL" },
    "STL": { name: "St. Louis Lambert International Airport", city: "St. Louis, MO" },
    "STT": { name: "Cyril E. King Airport", city: "St. Thomas, VI" },
    "STX": { name: "Henry E. Rohlsen Airport", city: "St. Croix, VI" },
    "SYR": { name: "Syracuse Hancock International Airport", city: "Syracuse, NY" },
    "TLH": { name: "Tallahassee International Airport", city: "Tallahassee, FL" },
    "TPA": { name: "Tampa International Airport", city: "Tampa, FL" },
    "TRI": { name: "Tri-Cities Regional Airport", city: "Bristol, TN" },
    "TUL": { name: "Tulsa International Airport", city: "Tulsa, OK" },
    "TUS": { name: "Tucson International Airport", city: "Tucson, AZ" },
    "TVC": { name: "Cherry Capital Airport", city: "Traverse City, MI" },
    "TYS": { name: "McGhee Tyson Airport", city: "Knoxville, TN" },
    "VPS": { name: "Destin-Fort Walton Beach Airport", city: "Destin, FL" },
    "XNA": { name: "Northwest Arkansas National Airport", city: "Fayetteville, AR" },
    // Aeropuertos adicionales que aparecen en aerolinea_origin_dest.json
    "ABE": { name: "Lehigh Valley International Airport", city: "Allentown, PA" },
    "ABY": { name: "Southwest Georgia Regional Airport", city: "Albany, GA" },
    "AEX": { name: "Alexandria International Airport", city: "Alexandria, LA" },
    "BGM": { name: "Greater Binghamton Airport", city: "Binghamton, NY" },
    "BQK": { name: "Brunswick Golden Isles Airport", city: "Brunswick, GA" },
    "CRW": { name: "Yeager Airport", city: "Charleston, WV" },
    "CSG": { name: "Columbus Metropolitan Airport", city: "Columbus, GA" },
    "CWA": { name: "Central Wisconsin Airport", city: "Wausau, WI" },
    "DHN": { name: "Dothan Regional Airport", city: "Dothan, AL" },
    "EVV": { name: "Evansville Regional Airport", city: "Evansville, IN" },
    "FWA": { name: "Fort Wayne International Airport", city: "Fort Wayne, IN" },
    "GFK": { name: "Grand Forks International Airport", city: "Grand Forks, ND" },
    "GTR": { name: "Golden Triangle Regional Airport", city: "Columbus, MS" },
    "ITH": { name: "Ithaca Tompkins Regional Airport", city: "Ithaca, NY" },
    "LAN": { name: "Capital Region International Airport", city: "Lansing, MI" },
    "LFT": { name: "Lafayette Regional Airport", city: "Lafayette, LA" },
    "MLI": { name: "Quad City International Airport", city: "Moline, IL" },
    "MLU": { name: "Monroe Regional Airport", city: "Monroe, LA" },
    "MGM": { name: "Montgomery Regional Airport", city: "Montgomery, AL" },
    "OAJ": { name: "Albert J. Ellis Airport", city: "Jacksonville, NC" },
    "ORH": { name: "Worcester Regional Airport", city: "Worcester, MA" },
    "PQI": { name: "Northern Maine Regional Airport", city: "Presque Isle, ME" },
    "PSE": { name: "Mercedita Airport", city: "Ponce, PR" },
    "RST": { name: "Rochester International Airport", city: "Rochester, MN" },
    "SCE": { name: "University Park Airport", city: "State College, PA" },
    "SJT": { name: "San Angelo Regional Airport", city: "San Angelo, TX" },
    "SPI": { name: "Abraham Lincoln Capital Airport", city: "Springfield, IL" },
    "SPS": { name: "Wichita Falls Regional Airport", city: "Wichita Falls, TX" },
    "STS": { name: "Charles M. Schulz Sonoma County Airport", city: "Santa Rosa, CA" },
    "TXK": { name: "Texarkana Regional Airport", city: "Texarkana, AR" },
    "TYR": { name: "Tyler Pounds Regional Airport", city: "Tyler, TX" },
    "VLD": { name: "Valdosta Regional Airport", city: "Valdosta, GA" },
    "XWA": { name: "Williston Basin International Airport", city: "Williston, ND" },
    "YUM": { name: "Yuma International Airport", city: "Yuma, AZ" },
    // Aeropuertos adicionales más comunes
    "ABI": { name: "Abilene Regional Airport", city: "Abilene, TX" },
    "ABR": { name: "Aberdeen Regional Airport", city: "Aberdeen, SD" },
    "ACK": { name: "Nantucket Memorial Airport", city: "Nantucket, MA" },
    "ACT": { name: "Waco Regional Airport", city: "Waco, TX" },
    "ACV": { name: "Arcata-Eureka Airport", city: "Arcata, CA" },
    "ACY": { name: "Atlantic City International Airport", city: "Atlantic City, NJ" },
    "ADK": { name: "Adak Airport", city: "Adak, AK" },
    "ADQ": { name: "Kodiak Airport", city: "Kodiak, AK" },
    "AKN": { name: "King Salmon Airport", city: "King Salmon, AK" },
    "ALO": { name: "Waterloo Regional Airport", city: "Waterloo, IA" },
    "APN": { name: "Alpena County Regional Airport", city: "Alpena, MI" },
    "ASE": { name: "Aspen/Pitkin County Airport", city: "Aspen, CO" },
    "ATY": { name: "Watertown Regional Airport", city: "Watertown, SD" },
    "AVP": { name: "Wilkes-Barre/Scranton International Airport", city: "Scranton, PA" },
    "AZA": { name: "Phoenix-Mesa Gateway Airport", city: "Mesa, AZ" },
    "AZO": { name: "Kalamazoo/Battle Creek International Airport", city: "Kalamazoo, MI" },
    "BET": { name: "Bethel Airport", city: "Bethel, AK" },
    "BFF": { name: "Western Nebraska Regional Airport", city: "Scottsbluff, NE" },
    "BFL": { name: "Meadows Field", city: "Bakersfield, CA" },
    "BIH": { name: "Eastern Sierra Regional Airport", city: "Bishop, CA" },
    "BJI": { name: "Bemidji Regional Airport", city: "Bemidji, MN" },
    "BLI": { name: "Bellingham International Airport", city: "Bellingham, WA" },
    "BLV": { name: "MidAmerica St. Louis Airport", city: "Belleville, IL" },
    "BMI": { name: "Central Illinois Regional Airport", city: "Bloomington, IL" },
    "BPT": { name: "Jack Brooks Regional Airport", city: "Beaumont, TX" },
    "BQN": { name: "Rafael Hernández Airport", city: "Aguadilla, PR" },
    "BRD": { name: "Brainerd Lakes Regional Airport", city: "Brainerd, MN" },
    "BRO": { name: "Brownsville/South Padre Island International Airport", city: "Brownsville, TX" },
    "BRW": { name: "Wiley Post-Will Rogers Memorial Airport", city: "Barrow, AK" },
    "BTM": { name: "Bert Mooney Airport", city: "Butte, MT" },
    "CAK": { name: "Akron-Canton Regional Airport", city: "Akron, OH" },
    "CDC": { name: "Cedar City Regional Airport", city: "Cedar City, UT" },
    "CDV": { name: "Merle K. (Mudhole) Smith Airport", city: "Cordova, AK" },
    "CIU": { name: "Chippewa County International Airport", city: "Sault Ste. Marie, MI" },
    "CKB": { name: "North Central West Virginia Airport", city: "Clarksburg, WV" },
    "CLD": { name: "McClellan-Palomar Airport", city: "Carlsbad, CA" },
    "CLL": { name: "Easterwood Airport", city: "College Station, TX" },
    "CMI": { name: "University of Illinois Willard Airport", city: "Champaign, IL" },
    "CMX": { name: "Houghton County Memorial Airport", city: "Hancock, MI" },
    "COD": { name: "Yellowstone Regional Airport", city: "Cody, WY" },
    "COU": { name: "Columbia Regional Airport", city: "Columbia, MO" },
    "CPR": { name: "Casper/Natrona County International Airport", city: "Casper, WY" },
    "CYS": { name: "Cheyenne Regional Airport", city: "Cheyenne, WY" },
    "DDC": { name: "Dodge City Regional Airport", city: "Dodge City, KS" },
    "DEC": { name: "Decatur Airport", city: "Decatur, IL" },
    "DIK": { name: "Dickinson Theodore Roosevelt Regional Airport", city: "Dickinson, ND" },
    "DLG": { name: "Dillingham Airport", city: "Dillingham, AK" },
    "DRO": { name: "Durango-La Plata County Airport", city: "Durango, CO" },
    "DVL": { name: "Devils Lake Regional Airport", city: "Devils Lake, ND" },
    "EAR": { name: "Kearney Regional Airport", city: "Kearney, NE" },
    "EAU": { name: "Chippewa Valley Regional Airport", city: "Eau Claire, WI" },
    "EKO": { name: "Elko Regional Airport", city: "Elko, NV" },
    "ELM": { name: "Elmira/Corning Regional Airport", city: "Elmira, NY" },
    "ESC": { name: "Delta County Airport", city: "Escanaba, MI" },
    "EWN": { name: "Coastal Carolina Regional Airport", city: "New Bern, NC" },
    "FLG": { name: "Flagstaff Pulliam Airport", city: "Flagstaff, AZ" },
    "FMN": { name: "Four Corners Regional Airport", city: "Farmington, NM" },
    "FNT": { name: "Bishop International Airport", city: "Flint, MI" },
    "FOD": { name: "Fort Dodge Regional Airport", city: "Fort Dodge, IA" },
    "FSM": { name: "Fort Smith Regional Airport", city: "Fort Smith, AR" },
    "GCC": { name: "Gillette-Campbell County Airport", city: "Gillette, WY" },
    "GCK": { name: "Garden City Regional Airport", city: "Garden City, KS" },
    "GGG": { name: "East Texas Regional Airport", city: "Longview, TX" },
    "GJT": { name: "Grand Junction Regional Airport", city: "Grand Junction, CO" },
    "GRI": { name: "Central Nebraska Regional Airport", city: "Grand Island, NE" },
    "GRK": { name: "Killeen-Fort Hood Regional Airport", city: "Killeen, TX" },
    "GST": { name: "Gustavus Airport", city: "Gustavus, AK" },
    "GTF": { name: "Great Falls International Airport", city: "Great Falls, MT" },
    "GUC": { name: "Gunnison-Crested Butte Regional Airport", city: "Gunnison, CO" },
    "GUF": { name: "Jack Edwards Airport", city: "Gulf Shores, AL" },
    "GUM": { name: "Antonio B. Won Pat International Airport", city: "Hagåtña, GU" },
    "HGR": { name: "Hagerstown Regional Airport", city: "Hagerstown, MD" },
    "HHH": { name: "Hilton Head Airport", city: "Hilton Head Island, SC" },
    "HIB": { name: "Range Regional Airport", city: "Hibbing, MN" },
    "HLN": { name: "Helena Regional Airport", city: "Helena, MT" },
    "HOB": { name: "Lea County Regional Airport", city: "Hobbs, NM" },
    "HTS": { name: "Tri-State Airport", city: "Huntington, WV" },
    "HYA": { name: "Barnstable Municipal Airport", city: "Hyannis, MA" },
    "HYS": { name: "Hays Regional Airport", city: "Hays, KS" },
    "IAG": { name: "Niagara Falls International Airport", city: "Niagara Falls, NY" },
    "IMT": { name: "Ford Airport", city: "Iron Mountain, MI" },
    "INL": { name: "Falls International Airport", city: "International Falls, MN" },
    "JLN": { name: "Joplin Regional Airport", city: "Joplin, MO" },
    "JMS": { name: "Jamestown Regional Airport", city: "Jamestown, ND" },
    "JST": { name: "John Murtha Johnstown-Cambria County Airport", city: "Johnstown, PA" },
    "KTN": { name: "Ketchikan International Airport", city: "Ketchikan, AK" },
    "LAF": { name: "Purdue University Airport", city: "Lafayette, IN" },
    "LAR": { name: "Laramie Regional Airport", city: "Laramie, WY" },
    "LAW": { name: "Lawton-Fort Sill Regional Airport", city: "Lawton, OK" },
    "LBE": { name: "Arnold Palmer Regional Airport", city: "Latrobe, PA" },
    "LBF": { name: "North Platte Regional Airport", city: "North Platte, NE" },
    "LBL": { name: "Liberal Mid-America Regional Airport", city: "Liberal, KS" },
    "LCH": { name: "Lake Charles Regional Airport", city: "Lake Charles, LA" },
    "LCK": { name: "Rickenbacker International Airport", city: "Columbus, OH" },
    "LNK": { name: "Lincoln Airport", city: "Lincoln, NE" },
    "LRD": { name: "Laredo International Airport", city: "Laredo, TX" },
    "LSE": { name: "La Crosse Regional Airport", city: "La Crosse, WI" },
    "LWS": { name: "Lewiston-Nez Perce County Airport", city: "Lewiston, ID" },
    "MBS": { name: "MBS International Airport", city: "Saginaw, MI" },
    "MCW": { name: "Mason City Municipal Airport", city: "Mason City, IA" },
    "MEI": { name: "Key Field", city: "Meridian, MS" },
    "MFE": { name: "McAllen Miller International Airport", city: "McAllen, TX" },
    "MFR": { name: "Rogue Valley International-Medford Airport", city: "Medford, OR" },
    "MGW": { name: "Morgantown Municipal Airport", city: "Morgantown, WV" },
    "MHK": { name: "Manhattan Regional Airport", city: "Manhattan, KS" },
    "MOT": { name: "Minot International Airport", city: "Minot, ND" },
    "MQT": { name: "Sawyer International Airport", city: "Marquette, MI" },
    "MRY": { name: "Monterey Regional Airport", city: "Monterey, CA" },
    "MVY": { name: "Martha's Vineyard Airport", city: "Vineyard Haven, MA" },
    "OTH": { name: "Southwest Oregon Regional Airport", city: "North Bend, OR" },
    "PBG": { name: "Plattsburgh International Airport", city: "Plattsburgh, NY" },
    "PGD": { name: "Punta Gorda Airport", city: "Punta Gorda, FL" },
    "PIA": { name: "General Wayne A. Downing Peoria International Airport", city: "Peoria, IL" },
    "PIB": { name: "Hattiesburg-Laurel Regional Airport", city: "Hattiesburg, MS" },
    "PIE": { name: "St. Pete-Clearwater International Airport", city: "Clearwater, FL" },
    "PIH": { name: "Pocatello Regional Airport", city: "Pocatello, ID" },
    "PIR": { name: "Pierre Regional Airport", city: "Pierre, SD" },
    "PLN": { name: "Pellston Regional Airport", city: "Pellston, MI" },
    "PRC": { name: "Ernest A. Love Field", city: "Prescott, AZ" },
    "PVU": { name: "Provo Municipal Airport", city: "Provo, UT" },
    "RDD": { name: "Redding Municipal Airport", city: "Redding, CA" },
    "RDM": { name: "Roberts Field", city: "Redmond, OR" },
    "RHI": { name: "Rhinelander-Oneida County Airport", city: "Rhinelander, WI" },
    "RIW": { name: "Central Wyoming Regional Airport", city: "Riverton, WY" },
    "RKS": { name: "Rock Springs-Sweetwater County Airport", city: "Rock Springs, WY" },
    "ROW": { name: "Roswell International Air Center", city: "Roswell, NM" },
    "SAF": { name: "Santa Fe Regional Airport", city: "Santa Fe, NM" },
    "SBP": { name: "San Luis Obispo County Regional Airport", city: "San Luis Obispo, CA" },
    "SGU": { name: "St. George Regional Airport", city: "St. George, UT" },
    "SHR": { name: "Sheridan County Airport", city: "Sheridan, WY" },
    "SLN": { name: "Salina Regional Airport", city: "Salina, KS" },
    "SPN": { name: "Francisco C. Ada Saipan International Airport", city: "Saipan, MP" },
    "STC": { name: "St. Cloud Regional Airport", city: "St. Cloud, MN" },
    "SUN": { name: "Friedman Memorial Airport", city: "Hailey, ID" },
    "SUX": { name: "Sioux Gateway Airport", city: "Sioux City, IA" },
    "SWO": { name: "Stillwater Regional Airport", city: "Stillwater, OK" },
    "SWF": { name: "Stewart International Airport", city: "Newburgh, NY" },
    "TOL": { name: "Toledo Express Airport", city: "Toledo, OH" },
    "TWF": { name: "Magic Valley Regional Airport", city: "Twin Falls, ID" },
    "TTN": { name: "Trenton-Mercer Airport", city: "Trenton, NJ" },
    "VCT": { name: "Victoria Regional Airport", city: "Victoria, TX" },
    "WYS": { name: "Yellowstone Airport", city: "West Yellowstone, MT" }
};

/**
 * Obtiene información de un aeropuerto por su código IATA
 * @param {string} iataCode - Código IATA del aeropuerto
 * @returns {object|null} - Objeto con name y city, o null si no se encuentra
 */
function getAirportInfo(iataCode) {
    if (!iataCode) return null;
    return AIRPORT_INFO[iataCode.toUpperCase()] || null;
}

/**
 * Formatea un código IATA de aeropuerto con su nombre y ciudad
 * @param {string} iataCode - Código IATA del aeropuerto
 * @param {string} name - Nombre del aeropuerto (opcional, se busca si no se proporciona)
 * @param {string} city - Ciudad del aeropuerto (opcional, se busca si no se proporciona)
 * @returns {string} - String formateado: "IATA - Nombre (Ciudad)"
 */
function formatAirportDisplay(iataCode, name, city) {
    if (!iataCode) return 'N/A';
    
    const info = getAirportInfo(iataCode);
    const airportName = name || (info ? info.name : null);
    const airportCity = city || (info ? info.city : null);
    
    if (airportName && airportCity) {
        return `${iataCode} - ${airportName} (${airportCity})`;
    } else if (airportName) {
        return `${iataCode} - ${airportName}`;
    } else if (airportCity) {
        return `${iataCode} (${airportCity})`;
    }
    return iataCode;
}

// Hacer disponible globalmente
window.AIRLINE_DATA = AIRLINE_DATA;
window.AIRPORT_INFO = AIRPORT_INFO;
window.getAirportInfo = getAirportInfo;
window.formatAirportDisplay = formatAirportDisplay;